version: '3'

services:
  adchpp:
    image: ivunchata/adchpp:3.0.0
    volumes:
      - ./etc/config:/app/config
      # - ./etc/certs:/app/certs
      # - ./etc/plugins:/app/plugins
      # - ./etc/scripts:/app/bin/scripts
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 2780:2780
