version: '3'

services:
  adchpp:
    build: .
    volumes:
      - ./etc/config:/app/config
      # - ./etc/certs:/app/certs
      # - ./etc/plugins:/app/plugins
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 2780:2780
